spring:
  datasource:
    #    测试库
    username: root
    password: whut.VINCENT920812
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://10.255.237.120:3306/zentaoep?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull
    url: jdbc:p6spy:mysql://10.255.237.120:3306/zentaoep?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=round
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1