# master 数据源配置

spring:
  datasource:
    dynamic:
      druid:
        #监控统计拦截的filters
        filters: stat
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/learn_mysql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: password
          driverClassName: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:33306/aaa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: 123456
          driverClassName: com.mysql.cj.jdbc.Driver

#master:
#  datasource:
#    url: jdbc:mysql://localhost:3306/learn_mysql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: root
#    password: password
#    driverClassName: com.mysql.cj.jdbc.Driver

# second 数据源配置
#second:
#  datasource:
#    url: jdbc:mysql://localhost:33306/aaa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    username: root
#    password: 123456
#    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 9999

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml


